<a href="https://colab.research.google.com/github/odellrb/Neural_Network_Charity_Analysis/blob/main/19_4_2_Deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

In [2]:
from google.colab import files
data_to_load = files.upload()

Saving HR-Employee-Attrition.csv to HR-Employee-Attrition.csv

In [3]:
# Import our input dataset
attrition_df = pd.read_csv('HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [5]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [8]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [9]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [11]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [12]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 2s 7ms/step - loss: 230.7562 - accuracy: 0.8276
Epoch 2/100
35/35 [==============================] - 0s 6ms/step - loss: 84.3841 - accuracy: 0.7659
Epoch 3/100
35/35 [==============================] - 0s 6ms/step - loss: 23.7841 - accuracy: 0.6978
Epoch 4/100
35/35 [==============================] - 0s 4ms/step - loss: 11.0022 - accuracy: 0.7051
Epoch 5/100
35/35 [==============================] - 0s 4ms/step - loss: 7.6907 - accuracy: 0.7414
Epoch 6/100
35/35 [==============================] - 0s 5ms/step - loss: 5.1544 - accuracy: 0.7314
Epoch 7/100
35/35 [==============================] - 0s 5ms/step - loss: 3.1921 - accuracy: 0.7377
Epoch 8/100
35/35 [==============================] - 0s 7ms/step - loss: 1.8697 - accuracy: 0.7314
Epoch 9/100
35/35 [==============================] - 0s 7ms/step - loss: 1.8822 - accuracy: 0.7414
Epoch 10/100
35/35 [==============================] - 0s 3ms/step - loss: 1.4806 - accuracy: 0.7196
Epoch 11/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1882 - accuracy: 0.7341
Epoch 12/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3112 - accuracy: 0.7387
Epoch 13/100
35/35 [==============================] - 0s 2ms/step - loss: 1.4181 - accuracy: 0.7341
Epoch 14/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3442 - accuracy: 0.7287
Epoch 15/100
35/35 [==============================] - 0s 2ms/step - loss: 1.6921 - accuracy: 0.7441
Epoch 16/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8907 - accuracy: 0.7541
Epoch 17/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8069 - accuracy: 0.7550
Epoch 18/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8785 - accuracy: 0.7586
Epoch 19/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9227 - accuracy: 0.7632
Epoch 20/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2681 - accuracy: 0.7541
Epoch 21/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7120 - accuracy: 0.7840
Epoch 22/100
35/35 [==============================] - 0s 3ms/step - loss: 1.1552 - accuracy: 0.7650
Epoch 23/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1668 - accuracy: 0.7641
Epoch 24/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2213 - accuracy: 0.7532
Epoch 25/100
35/35 [==============================] - 0s 2ms/step - loss: 1.3674 - accuracy: 0.7468
Epoch 26/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7176 - accuracy: 0.7922
Epoch 27/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7479 - accuracy: 0.7849
Epoch 28/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0509 - accuracy: 0.7523
Epoch 29/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6023 - accuracy: 0.7849
Epoch 30/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6619 - accuracy: 0.7868
Epoch 31/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7382 - accuracy: 0.7786
Epoch 32/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7371 - accuracy: 0.7740
Epoch 33/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.7931
Epoch 34/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6069 - accuracy: 0.7967
Epoch 35/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6706 - accuracy: 0.8004
Epoch 36/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9075 - accuracy: 0.7577
Epoch 37/100
35/35 [==============================] - 0s 2ms/step - loss: 1.2061 - accuracy: 0.7514
Epoch 38/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0350 - accuracy: 0.7759
Epoch 39/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8273 - accuracy: 0.7786
Epoch 40/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8373 - accuracy: 0.7813
Epoch 41/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6874 - accuracy: 0.7967
Epoch 42/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0870 - accuracy: 0.7695
Epoch 43/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6177 - accuracy: 0.8049
Epoch 44/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9016 - accuracy: 0.7677
Epoch 45/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8295 - accuracy: 0.7768
Epoch 46/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5756 - accuracy: 0.8049
Epoch 47/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7523 - accuracy: 0.7786
Epoch 48/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7664 - accuracy: 0.7849
Epoch 49/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7430 - accuracy: 0.7967
Epoch 50/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1315 - accuracy: 0.7632
Epoch 51/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0053 - accuracy: 0.7804
Epoch 52/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9095 - accuracy: 0.7641
Epoch 53/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7241 - accuracy: 0.7868
Epoch 54/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7159 - accuracy: 0.7831
Epoch 55/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5091 - accuracy: 0.8167
Epoch 56/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5366 - accuracy: 0.8149
Epoch 57/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5331 - accuracy: 0.8103
Epoch 58/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6075 - accuracy: 0.7940
Epoch 59/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5612 - accuracy: 0.8067
Epoch 60/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6407 - accuracy: 0.8040
Epoch 61/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9277 - accuracy: 0.7759
Epoch 62/100
35/35 [==============================] - 0s 3ms/step - loss: 1.1003 - accuracy: 0.7704
Epoch 63/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9226 - accuracy: 0.7722
Epoch 64/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6728 - accuracy: 0.7985
Epoch 65/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1251 - accuracy: 0.7586
Epoch 66/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8564 - accuracy: 0.7768
Epoch 67/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4342 - accuracy: 0.8303
Epoch 68/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6832 - accuracy: 0.7759
Epoch 69/100
35/35 [==============================] - 0s 3ms/step - loss: 0.6283 - accuracy: 0.8031
Epoch 70/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6656 - accuracy: 0.7913
Epoch 71/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6128 - accuracy: 0.8085
Epoch 72/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5723 - accuracy: 0.8040
Epoch 73/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4164 - accuracy: 0.8376
Epoch 74/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5409 - accuracy: 0.8085
Epoch 75/100
35/35 [==============================] - 0s 3ms/step - loss: 0.9191 - accuracy: 0.7632
Epoch 76/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7194 - accuracy: 0.8040
Epoch 77/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5953 - accuracy: 0.8076
Epoch 78/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4596 - accuracy: 0.8303
Epoch 79/100
35/35 [==============================] - 0s 3ms/step - loss: 0.4900 - accuracy: 0.8312
Epoch 80/100
35/35 [==============================] - 0s 2ms/step - loss: 0.7335 - accuracy: 0.8004
Epoch 81/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5110 - accuracy: 0.8267
Epoch 82/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4591 - accuracy: 0.8230
Epoch 83/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9441 - accuracy: 0.7913
Epoch 84/100
35/35 [==============================] - 0s 2ms/step - loss: 1.1215 - accuracy: 0.7677
Epoch 85/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5064 - accuracy: 0.8221
Epoch 86/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4875 - accuracy: 0.8312
Epoch 87/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6667 - accuracy: 0.8004
Epoch 88/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4473 - accuracy: 0.8394
Epoch 89/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8494
Epoch 90/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5576 - accuracy: 0.8122
Epoch 91/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5301 - accuracy: 0.8303
Epoch 92/100
35/35 [==============================] - 0s 2ms/step - loss: 0.4312 - accuracy: 0.8430
Epoch 93/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6236 - accuracy: 0.8049
Epoch 94/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6346 - accuracy: 0.8040
Epoch 95/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6824 - accuracy: 0.7985
Epoch 96/100
35/35 [==============================] - 0s 2ms/step - loss: 0.8656 - accuracy: 0.7777
Epoch 97/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6660 - accuracy: 0.7967
Epoch 98/100
35/35 [==============================] - 0s 2ms/step - loss: 0.9770 - accuracy: 0.7868
Epoch 99/100
35/35 [==============================] - 0s 2ms/step - loss: 0.6713 - accuracy: 0.8131
Epoch 100/100
35/35 [==============================] - 0s 2ms/step - loss: 1.0099 - accuracy: 0.7704

In [13]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 1s - loss: 0.6517 - accuracy: 0.8723 - 980ms/epoch - 82ms/step
Loss: 0.6516579985618591, Accuracy: 0.8722826242446899